kskwtnk/portfolio

src/pages/index.js
=> iPhone対応 refs #34

package-lock.json, package.json, yarn.lock
=> [#48]アラートの出ていたパッケージを更新

package.json, yarn.lock
=> [#50]アップデートし忘れていたパッケージに対応

src/components/footer.js, src/pages/index.js
=> [#44]footer追加

src/components/topTitle.js, src/pages/index.js
=> [#53]修正 & タイトルの表示変更

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, yarn.lock
=> [#55]redirect用のプラグイン導入

src/pages/about-me.js, src/pages/about-this-portfolio.js
=> [#70]description更新

src/pages/about-me.js, src/pages/about-this-portfolio.js
=> [#75]titleタグの中身を日本語に書き直した

gatsby-node.js
=> [#79]リダイレクト指定を変更

src/styles/Color.js
=> [#100]誤字修正

src/styles/Color.js
=> [#102]誤字修正

package.json, yarn.lock
=> [#112]Update gatsby-cli

package.json, yarn.lock
=> 121 remove unused packages

yarn.lock
=> [#124]Update gatsby-transformer-sharp

.stylelintrc, .vscode/settings.json
=> Change settings

.prettierrc, src/components/FigmaActivity.js
=> 143 improvement figma activity

src/components/FigmaActivity.js
=> 145 fix figma activity

gatsby-node.js, src/components/FigmaActivity.js
=> [#161] Update figma activity

src/components/FigmaActivity.js
=> Change figma activity style

src/components/FigmaActivity.js
=> [#168]Fix figma activity component

src/components/FigmaActivity.js
=> [#172]Fix date calculation in FigmaActivity component

gatsby-config.js, package.json, src/components/AdobeFonts.js, src/components/Seo.js, src/pages/404.js, yarn.lock
close #178 
- `react-helmet`を`react-helmet-async`へ変更
- `react-helmet`を削除
=> Solve warning about componentWillMount in react-helmet

package.json, src/components/Button.js, src/components/FigmaActivity.js, src/components/Footer.js, src/components/Header.js, src/components/Layout.js, src/components/ReleaseNotes.js, src/components/TopTitle.js, src/components/WorkTag.js, src/pages/404.js, src/pages/index.js, src/styles/GlobalStyle.js, src/styles/Theme.js, src/templates/workTemplate.js, yarn.lock
=> 179 organize library

src/components/Header.js, src/components/LinksToWork.js, src/templates/workTemplate.js
=> 199 style adjustment

src/pages/release-notes.js
=> [#202]Fix layout of release notes page

src/components/WorkSummary.js, src/components/WorkTag.js, src/markdown-pages/about-me/index.mdx, src/markdown-pages/about-this-portfolio/index.mdx, src/markdown-pages/arauhi/index.mdx, src/markdown-pages/ateam-desi-engineer-lt/index.mdx, src/markdown-pages/breath-m/index.mdx, src/markdown-pages/dasada-web-store/index.mdx, src/markdown-pages/media-engine-direction-system/index.mdx, src/markdown-pages/yuru-design-talk/index.mdx, src/templates/workTemplate.js
=> 222 update work tag

gatsby-config.js, gatsby-node.js, package.json, yarn.lock
=> [#196]Remove gatsby-plugin-netlify

package.json, pnpm-lock.yaml, src/pages/index.astro, src/styles/global.css
https://github.com/xrxoxcxox/portfolio/assets/22670303/437751db-30d4-4a60-a18d-5f340bf4a8e9
=> Top visual

src/content/works/portfolio/index.md, src/layouts/GlobalLayout.astro, src/pages/about-me/index.astro, src/pages/index.astro, src/pages/works/[...slug].astro
- Apply [Astro's View Transitions](https://docs.astro.build/en/guides/view-transitions/)
- Transition between top page and works page
- Update the contents of works/portfolio
=> Add view transitions and update contents

README.md, package.json, pnpm-lock.yaml, tsconfig.json
=> Fix omissions in #280

src/components/Footer.astro, src/data/works/figma-introduction-to-design/index.md, src/pages/index.astro
- Change of linked URLs in accordance with updated SNS IDs
=> Update SNS links

mise.toml
- Use [mise-en-plase](https://mise.jdx.dev/)
> [!NOTE]
=> Use mise-en-plase

eslint.config.js, package.json, pnpm-lock.yaml
- Upgrade ESLint and Prettier
- Update `eslint.config.js`
> [!NOTE]
=> Upgrade eslint and prettier

package.json, pnpm-lock.yaml
=> Upgrade Three.js

package.json, pnpm-lock.yaml
=> Upgrade sharp

package.json, pnpm-lock.yaml
- Upgrade @fontsource/shippori-mincho
> [!NOTE]
=> Upgrade @fontsource/shippori-mincho

package.json, pnpm-lock.yaml
- Upgrade Tailwind CSS and related packages
> [!NOTE]
=> Upgrade Tailwind CSS and related packages

package.json, pnpm-lock.yaml
=> Upgrade Astro

package.json, pnpm-lock.yaml
- Upgrade `three`
- https://github.com/mrdoob/three.js/wiki/Migration-Guide#176--177
> [!NOTE]
=> Upgrade three

.github/workflows/claude-code-review.yml, .github/workflows/claude.yml, CLAUDE.md
- Set up Claude Code
> [!NOTE]
=> Use claude code
